# Generated by Django 2.2 on 2019-04-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_column='S.No', max_length=5)),
                ('company', models.CharField(db_column='Traded Companies', max_length=60)),
                ('transactions', models.IntegerField(db_column='No of Transactions', max_length=10)),
                ('maxprice', models.FloatField(db_column='Max.Price', max_length=15)),
                ('minprice', models.FloatField(db_column='Min.Price', max_length=15)),
                ('closingprice', models.FloatField(db_column='Closing.Price', max_length=10)),
                ('tradedshares', models.IntegerField(db_column='Traded Shares', max_length=15)),
                ('amount', models.IntegerField(db_column='Traded Amount', max_length=15)),
                ('prevclosing', models.FloatField(db_column='Prev.Closing', max_length=10)),
                ('diff', models.FloatField(db_column='Diff.Rs.', max_length=6)),
            ],
        ),
    ]
