# Generated by Django 2.2 on 2019-04-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmovements', '0002_auto_20190423_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhead',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='closingprice',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='index',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='maxprice',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='minprice',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='prevclosing',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='tradedshares',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='transactions',
        ),
        migrations.AddField(
            model_name='stockhead',
            name='ClosingPrice',
            field=models.FloatField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='DiffRs',
            field=models.FloatField(default=1, max_length=6),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='MaxPrice',
            field=models.FloatField(default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='MinPrice',
            field=models.FloatField(default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='NoOfTransactions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='PrevClosing',
            field=models.FloatField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='SNo',
            field=models.IntegerField(db_column='S.No.', default=1),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='TradedAmount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='TradedCompanies',
            field=models.CharField(default='Abc', max_length=60),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='TradedShares',
            field=models.IntegerField(default=1),
        ),
    ]
