# Generated by Django 2.2 on 2019-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmovements', '0003_auto_20190423_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhead',
            name='SNo',
            field=models.IntegerField(),
        ),
    ]
