# Generated by Django 2.2 on 2019-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmovements', '0006_auto_20190424_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhead',
            name='NoOfTransactions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockhead',
            name='TradedAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockhead',
            name='TradedShares',
            field=models.IntegerField(),
        ),
    ]
