# Generated by Django 2.2 on 2019-04-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmovements', '0007_auto_20190424_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhead',
            name='ClosingPrice',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='DiffRs',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='MaxPrice',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='MinPrice',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='NoOfTransactions',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='PrevClosing',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='SNo',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='TradedAmount',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='TradedCompanies',
        ),
        migrations.RemoveField(
            model_name='stockhead',
            name='TradedShares',
        ),
        migrations.AddField(
            model_name='stockhead',
            name='album_title',
            field=models.CharField(default='Abc', max_length=100),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='artist',
            field=models.CharField(default='Abc', max_length=100),
        ),
        migrations.AddField(
            model_name='stockhead',
            name='genre',
            field=models.CharField(default='Abc', max_length=100),
        ),
    ]
