# Generated by Django 2.2 on 2019-04-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmovements', '0008_auto_20190425_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default='Abc', max_length=100)),
                ('album_title', models.CharField(default='Abc', max_length=100)),
                ('genre', models.CharField(default='Abc', max_length=100)),
                ('album_logo', models.CharField(default='Abc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=10)),
                ('song_title', models.CharField(max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmovements.Album')),
            ],
        ),
        migrations.DeleteModel(
            name='StockHead',
        ),
    ]
