# Generated by Django 2.2 on 2019-04-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmovements', '0009_auto_20190425_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='song',
        ),
    ]
