# Generated by Django 2.2 on 2019-04-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockmovements', '0010_auto_20190426_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='zodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_detail', models.TextField(default='You are going to have a sound health')),
            ],
        ),
    ]
