# Generated by Django 2.2 on 2019-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmovements', '0011_zodiac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='health_detail',
            field=models.TextField(),
        ),
    ]
